spring.application.name=helpdesk_system
spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk_db
spring.datasource.username=root
spring.datasource.password=1732050808Root@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000
jwt.refresh-expiration=604800000
app.cors.allowed-origins=http://localhost:3000
# Swagger UI t?i http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
spring.security.enabled=false